spring:
  config:
    import: optional:file:./config/secrets.yaml
  application:
    name: Instructors assignments
  datasource:
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: instructors_grades
        javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
        cache:
          use_second_level_cache: true
          region.factory_class: jcache
      org.hibernate.envers.default_schema: instructors_grades
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: instructors_grades
    schemas: instructors_grades
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    mini-app-url: ${TELEGRAM_MINI_APP_URL}
app:
  admin:
    login: ${ADMIN_LOGIN}
    password: ${ADMIN_PASSWORD}
  user:
    login: ${USER_LOGIN}
    password: ${USER_PASSWORD}
logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-history: 2
      max-file-size: 1MB
      total-size-cap: 100MB
  console:
    enabled: true
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE
    org.tourism.instructors: WARN
    org.tourism.instructors.application: INFO
    org.tourism.instructors.infrastructure.logging: INFO
