spring:
  application:
    name: publication-service
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: publication
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: publication
    schemas: publication
    fail-on-missing-locations: true
  kafka:
    consumer:
      group-id: publication-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.use.type.headers: false
        spring.json.value.default.type: org.tourism.publication.contract.ProtocolSnapshot
        spring.json.trusted.packages: org.tourism.publication.contract