CREATE SCHEMA IF NOT EXISTS instructors_grades AUTHORIZATION :app_user;

GRANT CONNECT ON DATABASE :db_name TO :app_user;
GRANT USAGE, CREATE ON SCHEMA instructors_grades TO :app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA instructors_grades
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA instructors_grades
    GRANT USAGE, SELECT ON SEQUENCES TO :app_user;