CREATE SCHEMA IF NOT EXISTS publication AUTHORIZATION :app_user;

REVOKE ALL ON DATABASE :db_name FROM PUBLIC;

GRANT CONNECT ON DATABASE :db_name TO :app_user;
GRANT USAGE, CREATE ON SCHEMA publication TO :app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA publication
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :app_user;
