-- туристы
CREATE TABLE IF NOT EXISTS instructors_grades.tourists
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name       VARCHAR(150),
    last_name        VARCHAR(150),
    middle_name      VARCHAR(150),
    gender           VARCHAR(6),
    date_of_birth    DATE,
    phone_number     VARCHAR(100),
    email            VARCHAR(100),
    certification_id VARCHAR(10)
);

-- контактная информация
CREATE TABLE IF NOT EXISTS instructors_grades.contact_info
(
    id         SERIAL PRIMARY KEY,
    type       VARCHAR(50),
    value      VARCHAR(100),
    details    VARCHAR,
    tourist_id INTEGER REFERENCES instructors_grades.tourists (id)
);

-- виды туризма
CREATE TABLE IF NOT EXISTS instructors_grades.kinds_of_tourism
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR,
    is_inactive BOOLEAN DEFAULT FALSE
);

-- звания
CREATE TABLE IF NOT EXISTS instructors_grades.grades
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR,
    expires_in  INT,
    is_inactive BOOLEAN DEFAULT FALSE
);

-- протоколы
CREATE TABLE IF NOT EXISTS instructors_grades.protocols
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number       VARCHAR(12),
    date         DATE,
    order_number VARCHAR(12),
    status       VARCHAR(20)
);

-- Табличная часть протокола "Туристы"
CREATE TABLE IF NOT EXISTS instructors_grades.protocols_content
(
    protocol_id      INT REFERENCES instructors_grades.protocols (id) ON DELETE CASCADE,
    row_num          INT CHECK (row_num > 0),
    tourist_id       INT REFERENCES instructors_grades.tourists (id),
    kind_of_tourism  INT REFERENCES instructors_grades.kinds_of_tourism (id),
    grade            INT REFERENCES instructors_grades.grades (id),
    certification_id VARCHAR(10),
    club             VARCHAR,
    decision_type    VARCHAR,
    PRIMARY KEY (protocol_id, row_num)
);
